from django.urls import path
from . import views
urlpatterns = [
    path("", views.index, name = "home"),
    path("pricing",views.pricing, name = "pricing"),
    path("go_premium",views.go_premium, name = "go_premium"),
    # path("all_properties", views.all_properties, name = "All_properties"),
    # path('accounts/signup',views.signup,name='signup'),
    # path("about", views.about, name='About'),
    # path("listing_prop_form_part_1", views.list_prop_1, name='List_prop_1'),
    # path("listing_prop_form_part_2", views.list_prop_2, name='List_prop_2'),
    # path("all_properties/property_view", views.property_view, name='Property_view'),
    path('pagedetail/<int:id>',views.page_detail,name='pagedetail'),
	path('faqs',views.faq_list,name='faq'),

    # path('accounts/login' , views.login_attempt , name="login"),
    path('register',views.register, name = "register"),
    path('login_attempt' , views.login_attempt , name="login"),
    path('otp/<uid>',views.otp , name = "otp"),
    path('forgot_password_otp/<uid>',views.forgot_password_otp , name = "forgot_password_otp"),
    path('add_new_password/<uid>',views.add_new_password , name = "add_new_password"),
    path('change_password' , views.change_password , name="change_password"),
    path('forgot_password' , views.forgot_password , name="forgot_password"),
    path('search_properties' , views.search_properties , name="search_properties"),
    path('search_properties/apply_filters', views.apply_filters, name= "apply_filters"),
    # path('rent_calculator' , views.rent_calculator , name="rent_calculator"),
    path('listed_properties' , views.listed_properties , name="listed_properties"),
    path('add_to_wishlist/<uid>' , views.add_to_wishlist , name="add_to_wishlist"),
    path('property_availability/<uid>' , views.property_availability , name="property_availability"),
    path('edit_property/<uid>' , views.edit_property , name="edit_property"),
    path('edit_property_photos/<uid>' , views.edit_property_photos , name="edit_property_photos"),
    path('show_property_photos/<uid>' , views.show_property_photos , name="show_property_photos"),
    path('delete_property/<uid>' , views.delete_property , name="delete_property"),
    path('delete_property_photo/<uid>/<int:id>' , views.delete_property_photo , name="delete_property_photo"),
    path('delete_account/<str:username>' , views.delete_account , name="delete_account"),
    path('wishlist', views.wishlist , name="wishlist"),
    path('view_messages', views.view_messages , name="view_messages"),
    path('create_chat_room/<uid>', views.create_chat_room , name="create_chat_room"),
    path('chat/<uid>/', views.chat , name="chat"),
    path('remove_from_wishlist/<uid>',views.remove_from_wishlist , name = "remove_from_wishlist"),
    path('remove_property_from_wishlist/<uid>',views.remove_property_from_wishlist , name = "remove_property_from_wishlist"),
    path('upload_images/<uid>',views.upload_images , name = "upload_images"),
    path('property_detailed_view/<uid>',views.single_property_view , name = "property_view"),
    path('logout_user', views.logout_view, name='logout_view'),   
    path('list_property', views.list_property, name = 'list_property'),
    path('dashboard', views.dashboard, name = 'dashboard'),
    path('dashboard/tenants/<uid>', views.view_tenants, name = 'view_tenants'),
    path('dashboard/tenant_details/<uid>', views.tenant_details, name = 'tenant_details'),
    path('dashboard/add_tenant/<uid>', views.add_tenants, name = 'add_tenant'),
    path('delete_tenant/<uid>', views.delete_tenant, name = 'delete_tenant')

    # path('accounts/otp/<uid>',views.otp , name = "otp"),
    # path('accounts/login-otp', views.login_otp , name="login_otp")   
]