# Generated by Django 4.1.9 on 2023-06-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_profile_user_alter_properties1_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='advance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='rent_collect',
            field=models.IntegerField(default=0),
        ),
    ]
