# Generated by Django 4.1.9 on 2023-06-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tenant_advance_alter_tenant_rent_collect'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=0)),
                ('amount_rec', models.IntegerField(default=0)),
                ('received_date', models.DateField()),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Collected')], default='0', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tenant')),
            ],
        ),
    ]
