# Generated by Django 4.1.9 on 2023-06-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tenantrentrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='rent_collect',
        ),
    ]
