# Generated by Django 4.1.9 on 2023-06-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_tenant_end_date_remove_tenant_rent_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='adhaar_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
