# Generated by Django 4.1.9 on 2023-06-24 04:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_tenant_adhaar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.plan'),
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertytitle', models.CharField(max_length=50, null=True)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('locality', models.CharField(max_length=30, null=True)),
                ('prefer_renter', models.CharField(choices=[('OB', 'Only Boys'), ('OG', 'Only Girls'), ('FAM', 'Family'), ('ANY', 'Anyone')], default='ANY', max_length=50, null=True)),
                ('pincode', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('rent', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('furnishing', models.CharField(blank=True, choices=[('FF', 'Fully-Furnished'), ('SF', 'Semi-Furnished'), ('UF', 'Un-Furnished')], max_length=50, null=True)),
                ('property_id', models.UUIDField(default=uuid.uuid4)),
                ('amenities', models.ManyToManyField(to='home.amenities')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categories')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.properties'),
        ),
        migrations.AlterField(
            model_name='room',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.properties'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.properties'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.properties'),
        ),
        migrations.DeleteModel(
            name='Properties1',
        ),
    ]
