# Generated by Django 4.1.9 on 2023-06-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_properties_latitude_alter_properties_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
    ]
