# Generated by Django 4.1.9 on 2023-07-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_properties_phone_no_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_visibility',
            field=models.BooleanField(default=True),
        ),
    ]
