# Generated by Django 4.1.9 on 2023-07-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_properties_property_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
